### ISSUE TITLE
Consistent Project.Json attributes

### ISSUE THREAD

**Issue by smudge202** [clean-development/engine#14]
The intent will be for the engine and all components to be shippable as NuGet packages. I'd like to see us making sure we have a consistent set of project.json attributes across all projects within the solution.

The following is my suggestion, very much open to debate/improvement:

``` json
{
    "version": "1.0.0-*",
    "description": "### for Clean Development Game Engine",
    "authors": [ "Project Author", "Contributors"  ],
    "tags": [ "###", "clean-development", "game", "engine" ],
    "projectUrl": "https://github.com/clean-development/engine",
    "licenseUrl": "https://raw.githubusercontent.com/clean-development/engine/master/LICENSE",
    "repository": {
        "type": "git",
        "url": "git://github.com/clean-development/engine"
    },
    "compilationOptions": {
        "warningsAsErrors": true
    }

```

In the above, replace `###` in the description with the pascal spaced project name i.e. "Component System" or "Event Stream".

Replace the '###' in the tags with the lower-hypenated project name i.e. "component-system" or "event-stream".

When adding a new project, set the `Project Author` to your name. When extending a project, add yourself as a contributor. I'm tempted to add the names of anyone that helps out in the pr reviews as a contributor (they are contributing...).

/2pence

**Comment by herecydev** [comment]
:shipit:
