### ISSUE TITLE
Rename Component System

### ISSUE THREAD

**Issue by smudge202** [clean-development/engine#22]
More than once the name of this project has caused issues due to it's ambiguity. The projects and associated meta need changing to `EntityComponentSystem`.

**Comment by ghost** [comment]
Could mark these sorts of things as help wanted. Its a nice way of getting new people into the project

**Comment by danielcirket** [comment]
I'll do this now as I've got a spare few minutes

**Comment by danielcirket** [comment]
See PR #23

**Comment by smudge202** [comment]
Resolved by #23
