### ISSUE TITLE
Setup CI pipeline

### ISSUE THREAD

**Issue by smudge202** [clean-development/engine#3]
AppVeyor would be the de facto choice, but I'm open to suggestion.

Assuming appveyor, we just need the `appveyor.yml` and any associated build scripts. I'll get an account setup for the organisation in due course.

**Comment by herecydev** [comment]
If you script the majority and bundle that into your source code, you will keep the vendor-specific stuff minimal. This helps inclusion of [travis](https://travis-ci.org/) or other CI tools. That way you can setup all of them to run and just let it be a free-for-all.

With minimal extra cost you get faster feedback (first return will suggest a positive result), more consistency (A failing build on 1 CI indicates "it worked on my machine" problem), and failover.

**Comment by smudge202** [comment]
Agreed; I want all the important stuff in build scripts. However, should we find ourselves using API keys or something of that nature that requires the use of [secrets manager](https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration) that will have to be bespoke to the build agent acounts.

**Comment by smudge202** [comment]
Blocked by #2
