### ISSUE TITLE
Internal Event Bus

### ISSUE THREAD

**Issue by smudge202** [clean-development/engine#7]
The engine is intended to be entirely event sourced. As such, we'll need at the very least an in-memory implementation. I'll try to define some bounds to help flesh this item out:
- Abstractions need to be ambiguous enough to allow for the following implementation types:
  - In-Memory (non-persistent)
  - _On-Prem_ persistent/reliable messaging systems (NServiceBus, RabbitMQ, etc.)
  - Cloud Services (Azure Topics, Event Hub, etc.)
  - The in-memory implementation (we'll defer introducing the third party technologies until necessary)
  - Concurrency - this needs to be cooked in, even for the in-memory implementation. Testing this stuff is no fun, so we'll probably need to be a little creative in integration tests.
  - Akin #6, we'll want some form of stress/load testing. There are no benchmarks we're aiming for, we simply want to benchmark and monitor the performance.

Just to help summarise comments below and track future work, I'm going to add a tally to this issue which I'll update before merging any Pull Requests. The table will simply name classes (consumers of the bus) that fall into the respective columns:

| Publish Only | Subscribe Only | Publish & Subscribe Different Types | Publish & Subscribe Same Types |
| --- | --- | --- | --- |
| N/A | N/A | N/A | N/A |

**Comment by herecydev** [comment]
Can probably achieve this easily with an internal project we're maintaining at the moment. Perhaps I can get it OS'd.

**Comment by ghost** [comment]
Should be fairly easy to write that into it, certainly what I am thinking along the lines of anyway.

To catch up from [Twitter discussions](https://twitter.com/Smudge202/status/657271310108770304):
- Bus should not have class level generic so you can add events easily without adding Bus<T> everywhere or w/e its going to be finally called
- There should be no marking of events, so we can send any POCO

Thinking the initial API will look something like this (name not decided, will probably change):

``` c#
public interface EventStream
{
  void Dispatch<T>(T entity);
  IDisposable Subscribe<T>(IObserver<T> observer);
}
```

_Will add more of the convo as/when_

_EDIT: Changed your code snippet from stackoverflow syntax to GFM - Tommy_

**Comment by smudge202** [comment]
Interface looks good; naming I appreciate is subject to change but otherwise it's what I had in mind.

As per @herecydev on Twitter, possibly the following interface would lean towards cleaner practices (SRP):

``` c#
public interface EventStream<T>
{
  void Dispatch(T entity);
  void Subscribe(IObserver<T> subscriber);
}
```

For now, I think we'll take the method level generics on the premise that if we get to v1 without a legitimate usage of method level (conforming to SRP), then I'll personally switch the interface and all usages.

Similarly, it may be worth examining whether the Subscribe/Publish can conform with Interface Segregation (i.e. split to two interfaces) but only if we don't have any consumers that perform both operations.

I see typical usage being Subscribe For TypeA, Publish TypeB which would support the interface split, but we'll see how things go.

**Comment by smudge202** [comment]
Before I forget... I have an AWESOME series of code I wrote at work that allows for Subscriptions to be declared during composition without instantiating the event bus OR the subscriber. Essentially adds a load of deferred realization meta to the `IServiceCollection` plus the necessary magic to fire it up when the EventBus is required.

I need to speak to my boss to see if he minds me borrowing it. Implementing it the first time was a NIGHTMARE so I'd hate to have to do it again from scratch.

**Comment by danielcirket** [comment]
Seems like we've all written things that are similar to what we need / can borrow from for the engine :+1: 

Leaving this: http://git.io/vWCFJ for reference in case any parts may be useful - I doubt it but it all helps

**Comment by smudge202** [comment]
//cc @shaundodimead - do you mind if I borrow the `ServiceExtensions` class from the EventBus project I added last week (possibly also the EventBus implementation too)?

@danielcirket which is beautiful because the code we refine as a group here, can be taken back into said work projects if we come up with improvements / useful additions. :)

**Comment by ghost** [comment]
OSS all the things. I've actually got it split into two interfaces at the moment (EventProducer / EventStream -> Sending/Receiving). Keeping it method level at the moment but should be easy change to move to the class level as per discussion above.

**Comment by ghost** [comment]
As noted to Smudge:

The only thing is that with splitting out the interfaces you could potentially get into a situation where you override the default in memory stream with a azure one (eg) but leave the producer as the in memory -> never getting messages. But cant really stop stupidity.

Basic abstraction/tests to get us going pretty much done.

**Comment by smudge202** [comment]
Reference material signed off by Gilmond: https://gist.github.com/smudge202/7c426c5295a5136c5489
